name: publish

on:
  push:
    branches:
    - 'main' # TODO support tagging configs with the branch

jobs:
  publish:
    runs-on: ubuntu-slim
    steps:
    - name: Checkout
      uses: actions/checkout@v7
    # - name: Install AWS CLI
    #   run: |
    #     curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
    #     unzip awscliv2.zip
    #     ./aws/install
    - name: Sync configs
      env:
        BUCKET: ${{ secrets.OGSH_CONFIG_S3_BUCKET }}
        ENDPOINT: ${{ secrets.OGSH_CONFIG_S3_ENDPOINT }}
        REGION: ${{ secrets.OGSH_CONFIG_S3_REGION }}
        AWS_ACCESS_KEY_ID: ${{ secrets.OGSH_CONFIG_S3_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.OGSH_CONFIG_S3_SECRET_ACCESS_KEY }}
      run: aws s3 sync ./configs s3://$BUCKET/ogsh-configs --delete --region $REGION --endpoint-url $ENDPOINT